//
//  XJJNewsModel.swift
//  XJJSwiftDome
//
//  Created by Levy on 2021/2/26.
//

import Foundation
import UIKit

class XJJNewsModel {
    var dataSource: [XJJNewsItem.ID: XJJNewsItem] = [:] // 数据
}

extension XJJNewsModel {
    
    func getDataSource() {
        let text_font = XJJThemeConfig.share.theme.page_text[.text]?.font ?? UIFont.systemFont(ofSize: 15)
        let random = XJJThemeConfig.share.theme.page_text[.randomText] ?? XJJText(randomType: XJJText.TRandom(fontSize: (14, 15), fontArr: [text_font.fontName]))
        
        self.dataSource = [
            XJJNewsItem.ID.first: XJJNewsTableItem(id: .first, data: [
                XJJNewsTableSubItem(one: XJJText(range: "震惊！！！今年15岁的男孩，5年前尽然才10岁！！！", attrArr: [XJJText.TRange(index: 0, count: 5, color: UIColor.red, font: text_font), XJJText.TRange(index: 5, count: 50, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("天书奇谈"),
                                    tip: XJJText("这是个笑话", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(range: "遗憾！！！年仅30岁的他为了这个世界，献出了所有！！！", attrArr: [XJJText.TRange(index: 0, count: 5, color: UIColor.red, font: text_font), XJJText.TRange(index: 5, count: 50, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("天书奇谈"),
                                    tip: XJJText("时事实说", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(designated: "520 看过来！！！教你怎么找对象！！！", attrArr: [XJJText.TDesignated(designated: XJJText.numbers, color: UIColor.randomColor, font: text_font), XJJText.TDesignated(designated: "你我他她", color: UIColor.purple, font: UIFont(name: text_font.fontName, size: 18) ?? text_font), XJJText.TDesignated(designated: XJJText.designatedAll, color: UIColor.darkText, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("奇思妙想"),
                                    tip: XJJText("爱你一万年", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(range: "震惊！！！今年15岁的男孩，5年前尽然才10岁！！！", attrArr: [XJJText.TRange(index: 0, count: 5, color: UIColor.red, font: text_font), XJJText.TRange(index: 5, count: 50, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("天书奇谈"),
                                    tip: XJJText("这是个笑话", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(range: "震惊！！！今年15岁的男孩，5年前尽然才10岁！！！", attrArr: [XJJText.TRange(index: 0, count: 5, color: UIColor.red, font: text_font), XJJText.TRange(index: 5, count: 50, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("天书奇谈"),
                                    tip: XJJText("这是个笑话", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(range: "震惊！！！今年15岁的男孩，5年前尽然才10岁！！！", attrArr: [XJJText.TRange(index: 0, count: 5, color: UIColor.red, font: text_font), XJJText.TRange(index: 5, count: 50, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("天书奇谈"),
                                    tip: XJJText("这是个笑话", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(range: "震惊！！！今年15岁的男孩，5年前尽然才10岁！！！", attrArr: [XJJText.TRange(index: 0, count: 5, color: UIColor.red, font: text_font), XJJText.TRange(index: 5, count: 50, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("天书奇谈"),
                                    tip: XJJText("这是个笑话", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(range: "震惊！！！今年15岁的男孩，5年前尽然才10岁！！！", attrArr: [XJJText.TRange(index: 0, count: 5, color: UIColor.red, font: text_font), XJJText.TRange(index: 5, count: 50, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("天书奇谈"),
                                    tip: XJJText("这是个笑话", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(range: "震惊！！！今年15岁的男孩，5年前尽然才10岁！！！", attrArr: [XJJText.TRange(index: 0, count: 5, color: UIColor.red, font: text_font), XJJText.TRange(index: 5, count: 50, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("天书奇谈"),
                                    tip: XJJText("这是个笑话", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(range: "震惊！！！今年15岁的男孩，5年前尽然才10岁！！！", attrArr: [XJJText.TRange(index: 0, count: 5, color: UIColor.red, font: text_font), XJJText.TRange(index: 5, count: 50, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("天书奇谈"),
                                    tip: XJJText("这是个笑话", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(range: "遗憾！！！年仅30岁的他为了这个世界，献出了所有！！！", attrArr: [XJJText.TRange(index: 0, count: 5, color: UIColor.red, font: text_font), XJJText.TRange(index: 5, count: 50, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("天书奇谈"),
                                    tip: XJJText("时事实说", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(range: "震惊！！！今年15岁的男孩，5年前尽然才10岁！！！", attrArr: [XJJText.TRange(index: 0, count: 5, color: UIColor.red, font: text_font), XJJText.TRange(index: 5, count: 50, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("天书奇谈"),
                                    tip: XJJText("这是个笑话", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(range: "震惊！！！今年15岁的男孩，5年前尽然才10岁！！！", attrArr: [XJJText.TRange(index: 0, count: 5, color: UIColor.red, font: text_font), XJJText.TRange(index: 5, count: 50, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("天书奇谈"),
                                    tip: XJJText("这是个笑话", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(range: "震惊！！！今年15岁的男孩，5年前尽然才10岁！！！", attrArr: [XJJText.TRange(index: 0, count: 5, color: UIColor.red, font: text_font), XJJText.TRange(index: 5, count: 50, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("天书奇谈"),
                                    tip: XJJText("这是个笑话", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(range: "震惊！！！今年15岁的男孩，5年前尽然才10岁！！！", attrArr: [XJJText.TRange(index: 0, count: 5, color: UIColor.red, font: text_font), XJJText.TRange(index: 5, count: 50, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("天书奇谈"),
                                    tip: XJJText("这是个笑话", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(range: "震惊！！！今年15岁的男孩，5年前尽然才10岁！！！", attrArr: [XJJText.TRange(index: 0, count: 5, color: UIColor.red, font: text_font), XJJText.TRange(index: 5, count: 50, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("天书奇谈"),
                                    tip: XJJText("这是个笑话", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(range: "震惊！！！今年15岁的男孩，5年前尽然才10岁！！！", attrArr: [XJJText.TRange(index: 0, count: 5, color: UIColor.red, font: text_font), XJJText.TRange(index: 5, count: 50, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("天书奇谈"),
                                    tip: XJJText("这是个笑话", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(range: "震惊！！！今年15岁的男孩，5年前尽然才10岁！！！", attrArr: [XJJText.TRange(index: 0, count: 5, color: UIColor.red, font: text_font), XJJText.TRange(index: 5, count: 50, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("天书奇谈"),
                                    tip: XJJText("这是个笑话", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(range: "震惊！！！今年15岁的男孩，5年前尽然才10岁！！！", attrArr: [XJJText.TRange(index: 0, count: 5, color: UIColor.red, font: text_font), XJJText.TRange(index: 5, count: 50, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("天书奇谈"),
                                    tip: XJJText("这是个笑话", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(range: "震惊！！！今年15岁的男孩，5年前尽然才10岁！！！", attrArr: [XJJText.TRange(index: 0, count: 5, color: UIColor.red, font: text_font), XJJText.TRange(index: 5, count: 50, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("天书奇谈"),
                                    tip: XJJText("这是个笑话", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(designated: "520 看过来！！！教你怎么找对象！！！", attrArr: [XJJText.TDesignated(designated: XJJText.numbers, color: UIColor.randomColor, font: text_font), XJJText.TDesignated(designated: "你我他她", color: UIColor.purple, font: UIFont(name: text_font.fontName, size: 18) ?? text_font), XJJText.TDesignated(designated: XJJText.designatedAll, color: UIColor.darkText, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("奇思妙想"),
                                    tip: XJJText("爱你一万年", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(range: "震惊！！！今年15岁的男孩，5年前尽然才10岁！！！", attrArr: [XJJText.TRange(index: 0, count: 5, color: UIColor.red, font: text_font), XJJText.TRange(index: 5, count: 50, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("天书奇谈"),
                                    tip: XJJText("这是个笑话", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(range: "震惊！！！今年15岁的男孩，5年前尽然才10岁！！！", attrArr: [XJJText.TRange(index: 0, count: 5, color: UIColor.red, font: text_font), XJJText.TRange(index: 5, count: 50, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("天书奇谈"),
                                    tip: XJJText("这是个笑话", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(range: "震惊！！！今年15岁的男孩，5年前尽然才10岁！！！", attrArr: [XJJText.TRange(index: 0, count: 5, color: UIColor.red, font: text_font), XJJText.TRange(index: 5, count: 50, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("天书奇谈"),
                                    tip: XJJText("这是个笑话", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200),
                XJJNewsTableSubItem(one: XJJText(range: "震惊！！！今年15岁的男孩，5年前尽然才10岁！！！", attrArr: [XJJText.TRange(index: 0, count: 5, color: UIColor.red, font: text_font), XJJText.TRange(index: 5, count: 50, font: text_font)]),
                                    imageArr: [],
                                    origin: random.newText("天书奇谈"),
                                    tip: XJJText("这是个笑话", color: XJJThemeConfig.share.theme.page_color[.tip], font: text_font),
                                    cellHeight: 200)
            ])
        
        ]
    }
}
